import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Noto_Sans } from "next/font/google";

import "./globals.css";

const noto = Noto_Sans({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
  variable: "--noto-sans",
});

export const metadata: Metadata = {
  title: "picbook-home",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={noto.className}>
          <div className="mx-auto flex max-w-6xl">
            <main className="flex min-h-screen w-full">
              {children}
            </main>
          </div>
        </body>
      </SessionProvider>
    </html>
  );
}
