import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import NextAuthProvider from "@/lib/auth/NextAuthProvider";
import { NextThemeProvider } from "@/lib/theme/NextThemesProvider";

import Sider from "./_components/Sider";
import "./globals.css";

const noto = Noto_Sans({
  subsets: ["latin-ext"],
  weight: ["400", "700"],
  variable: "--noto-sans",
});

export const metadata: Metadata = {
  title: "PicPick",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={noto.className}>
          <div className="mx-auto flex">
            <NextThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
            >
              <Sider />
              <main className="flex max-h-screen w-full overflow-y-scroll">
                {children}
              </main>
            </NextThemeProvider>
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
